groups:
  A: "^[0-9]$"
  B: "^1[0-9]$"
  cell0: "^0$"
  cell34: "^34$"
  all: ".*"

datasets:
  140genesData:
    dist: 4
    N: 16
    m: 4
    err01: [0.016, 0.015, 0.021, 0.015, 0.051, 0.065, 0.062, 0.026, 0.019, 0.021, 0.023, 0.034, 0.02, 0.029, 0.07, 0.027]
    err10: [0.05, 0.04, 0.065, 0.052, 0.177, 0.135, 0.155, 0.07, 0.053, 0.057, 0.066, 0.09, 0.069, 0.07, 0.145, 0.103]
    has_corrected: true
    experiments: 7
  1001genesData:
    dist: 2
    N: 14
    m: 4
    err01: 0.04
    err10: 0.1
    has_corrected: false
    experiments: 3
  simulated-MHD4:
    dist: 4
    N: 16
    m: 4
    err01: 0.04
    err10: 0.1
    has_corrected: true
    experiments: 1
  simulated-MHD2:
    dist: 2
    N: 14
    m: 4
    err01: 0.04
    err10: 0.1
    has_corrected: false
    experiments: 1
  simulated-MHD4-4:
    dist: 4
    N: 16
    m: 4
    err01: 0.005
    err10: 0.01
    has_corrected: true
    experiments: 1
  simulated-MHD4-6:
    dist: 4
    N: 16
    m: 6
    err01: 0.005
    err10: 0.01
    has_corrected: true
    experiments: 1
  simulated-MHD4-8:
    dist: 4
    N: 16
    m: 8
    err01: 0.005
    err10: 0.01
    has_corrected: true
    experiments: 1
  simulated-MHD2-4:
    dist: 2
    N: 16
    m: 4
    err01: 0.005
    err10: 0.01
    has_corrected: false
    experiments: 1
  simulated-MHD2-6:
    dist: 2
    N: 16
    m: 6
    err01: 0.005
    err10: 0.01
    has_corrected: false
    experiments: 1
  simulated-MHD2-8:
    dist: 2
    N: 16
    m: 8
    err01: 0.005
    err10: 0.01
    has_corrected: false
    experiments: 1

codebooks:
  140genesData:
    1: codebook/140genesData.1.txt
    2: codebook/140genesData.2.txt
    3: codebook/140genesData.1.txt
    4: codebook/140genesData.2.txt
    5: codebook/140genesData.2.txt
    6: codebook/140genesData.1.txt
    7: codebook/140genesData.1.txt
  1001genesData:
    1: codebook/1001genesData.txt
    2: codebook/1001genesData.txt
    3: codebook/1001genesData.txt
  simulated-MHD4: codebook/simulated-MHD4.txt
  simulated-MHD2: codebook/simulated-MHD2.txt
  simulated-MHD4-4: codebook/simulated-MHD4-4.txt
  simulated-MHD4-6: codebook/simulated-MHD4-6.txt
  simulated-MHD4-8: codebook/simulated-MHD4-8.txt
  simulated-MHD2-4: codebook/simulated-MHD2-4.txt
  simulated-MHD2-6: codebook/simulated-MHD2-6.txt
  simulated-MHD2-8: codebook/simulated-MHD2-8.txt

error-rates:
  codebook/140genesData.1.txt:
    err01: [0.016, 0.015, 0.021, 0.015, 0.051, 0.065, 0.062, 0.026, 0.019, 0.021, 0.023, 0.034, 0.02, 0.029, 0.07, 0.027]
    err10: [0.05, 0.04, 0.065, 0.052, 0.177, 0.135, 0.155, 0.07, 0.053, 0.057, 0.066, 0.09, 0.069, 0.07, 0.145, 0.103]
  codebook/140genesData.2.txt:
     err01: [0.022, 0.027, 0.015, 0.019, 0.09, 0.025, 0.02, 0.033, 0.027, 0.035, 0.037, 0.037 , 0.07, 0.085, 0.034, 0.092]
     err10: [0.053, 0.06, 0.04, 0.04, 0.168, 0.06, 0.043, 0.07, 0.06, 0.073, 0.069, 0.056, 0.16, 0.17, 0.065, 0.182]
  codebook/1001genesData.txt:
    err01: [0.04]
    err10: [0.1]
  codebook/simulated-MHD4.txt:
    err01: [0.04]
    err10: [0.1]
  codebook/simulated-MHD2.txt:
    err01: [0.04]
    err10: [0.1]
  codebook/simulated-MHD4-4.txt:
    err01: [0.005]
    err10: [0.01]
  codebook/simulated-MHD4-6.txt:
    err01: [0.005]
    err10: [0.01]
  codebook/simulated-MHD4-8.txt:
    err01: [0.005]
    err10: [0.01]
  codebook/simulated-MHD2-4.txt:
    err01: [0.005]
    err10: [0.01]
  codebook/simulated-MHD2-6.txt:
    err01: [0.005]
    err10: [0.01]
  codebook/simulated-MHD2-8.txt:
    err01: [0.005]
    err10: [0.01]

settings:
  default:
    err01-factor: 1.0
    err10-factor: 1.0
  err-5%:
    err01-factor: 0.95
    err10-factor: 0.95
  err-10%:
    err01-factor: 0.9
    err10-factor: 0.9
  err-20%:
    err01-factor: 0.8
    err10-factor: 0.8
  err-30%:
    err01-factor: 0.7
    err10-factor: 0.7

plots:
  figsize: [2.4, 2]
