name: merfishtools
channels:
- r
- bioconda
- pkgw
dependencies:
- bioconductor-biomart=2.26.1
- bioconductor-gostats=2.36.0
- bioconductor-multtest=2.26.0
- bioconductor-go.db=3.2.2
- bioconductor-org.hs.eg.db=3.2.3
- r-mutoss=0.1
- matplotlib=1.5.1
- merfishtools=0.9.1
- numpy=1.11.0
- pandas=0.18.1
- pyyaml=3.11
- rpy2=2.7.8
- scikit-learn=0.17.1
- scipy=0.17.0
- seaborn=0.7.0
- snakemake=3.7.0
- statsmodels=0.6.1
- svgutils=0.1.0
- librsvg=2.40.13
