name: merfishtools
channels:
- r
- bioconda
- ostrokach
dependencies:
- at-spi2-atk=2.16.0
- at-spi2-core=2.16.0
- atk=2.16.0
- bioconductor-annotate=1.48.0
- bioconductor-annotationdbi=1.32.3
- bioconductor-annotationforge=1.12.2
- bioconductor-biobase=2.30.0
- bioconductor-biocgenerics=0.16.1
- bioconductor-biomart=2.26.1
- bioconductor-category=2.36.0
- bioconductor-genefilter=1.52.1
- bioconductor-go.db=3.2.2
- bioconductor-gostats=2.36.0
- bioconductor-graph=1.48.0
- bioconductor-gseabase=1.32.0
- bioconductor-iranges=2.4.8
- bioconductor-multtest=2.26.0
- bioconductor-org.hs.eg.db=3.2.3
- bioconductor-rbgl=1.46.0
- bioconductor-rgraphviz=2.14.0
- bioconductor-s4vectors=0.8.11
- bison=3.0.4
- bitarray=0.8.1
- boto=2.39.0
- cairo=1.12.18
- curl=7.45.0
- cycler=0.10.0
- dbus=1.8.20
- dbus-glib=0.104
- docutils=0.12
- dropbox=5.2.1
- ecdsa=0.13
- expat=2.1.0
- filechunkio=1.6
- flask=0.10.1
- flex=2.5.39
- fontconfig=2.11.1
- freetype=2.5.5
- ftputil=3.2
- gdk-pixbuf=2.30.8
- gettext=0.19.5
- glib=2.44.1
- gobject-introspection=1.44.0
- gsl=1.16
- gtk=3.16.6
- harfbuzz=1.0.1
- httpretty=0.8.14
- icu=55.1
- itsdangerous=0.24
- jbig=2.1
- jinja2=2.8
- jpeg=8d
- libcroco=0.6.8
- libepoxy=1.3.1
- libffi=3.2.1
- libgcc=5.2.0
- libgfortran=3.0
- libgsf=1.14.34
- libpng=1.6.17
- librsvg=2.40.10
- libsigcpp=2.4.1
- libtiff=4.0.6
- libxml2=2.9.3
- libxslt=1.1.28
- lxml=3.6.0
- markupsafe=0.23
- matplotlib=1.5.1
- merfishtools=0.9.1
- mkl=11.3.1
- moto=0.4.14
- ncurses=5.9
- nomkl=1.0
- numpy=1.11.0
- openblas=0.2.14
- openssl=1.0.2h
- pandas=0.18.1
- pango=1.39.0
- paramiko=1.16.0
- patsy=0.4.1
- pcre=8.31
- pip=8.1.1
- pixman=0.32.6
- pycrypto=2.6.1
- pyparsing=2.1.1
- pyqt=4.11.4
- pysftp=0.2.8
- python=3.5.1
- python-dateutil=2.5.2
- pytz=2016.3
- pyyaml=3.11
- qt=4.8.7
- r=3.2.2
- r-base=3.2.2
- r-bitops=1.0_6
- r-boot=1.3_17
- r-class=7.3_14
- r-cluster=2.0.3
- r-codetools=0.2_14
- r-colorspace=1.2_6
- r-dbi=0.3.1
- r-dichromat=2.0_0
- r-digest=0.6.9
- r-doparallel=1.0.10
- r-foreach=1.4.3
- r-foreign=0.8_66
- r-ggplot2=2.1.0
- r-gridbase=0.4_7
- r-gtable=0.1.2
- r-igraph=1.0.1
- r-irlba=2.0.0
- r-iterators=1.0.8
- r-kernsmooth=2.23_15
- r-labeling=0.3
- r-lattice=0.20_33
- r-magrittr=1.5
- r-mass=7.3_45
- r-matrix=1.2_2
- r-mgcv=1.8_9
- r-multcomp=1.4_1
- r-munsell=0.4.2
- r-mutoss=0.1_10
- r-mvtnorm=1.0_3
- r-nlme=3.1_122
- r-nmf=0.20.6
- r-nnet=7.3_11
- r-pkgmaker=0.22
- r-plotrix=3.6_1
- r-plyr=1.8.3
- r-rcolorbrewer=1.1_2
- r-rcpp=0.12.2
- r-rcurl=1.95_4.7
- r-recommended=3.2.2
- r-registry=0.3
- r-reshape2=1.4.1
- r-rngtools=1.2.4
- r-rpart=4.1_10
- r-rsqlite=1.0.0
- r-sandwich=2.3_4
- r-scales=0.3.0
- r-spatial=7.3_11
- r-stringi=1.0_1
- r-stringr=1.0.0
- r-survival=2.38_3
- r-th.data=1.0_6
- r-xml=3.98_1.3
- r-xtable=1.8_0
- r-zoo=1.7_12
- readline=6.2
- requests=2.9.1
- rpy2=2.7.8
- rust=1.6.0
- scikit-learn=0.17.1
- scipy=0.17.0
- seaborn=0.7.0
- setuptools=20.7.0
- sip=4.16.9
- six=1.10.0
- snakemake=3.7.0
- sqlite=3.9.2
- statsmodels=0.6.1
- svgutils=0.1.0
- system=5.8
- tk=8.5.18
- urllib3=1.12
- werkzeug=0.11.8
- wheel=0.29.0
- xmltodict=0.9.2
- xz=5.0.5
- yaml=0.1.6
- zlib=1.2.8

