channels:
  - bioconda
  - ostrokach
dependencies:
  - python ==3.5.1
  - numpy ==1.10.4
  - matplotlib ==1.5.1
  - snakemake ==3.6.1
  - scikit-learn ==0.17.1
  - scipy ==0.17.0
  - pandas ==0.17.1
  - seaborn ==0.7.0
  - bitarray ==0.8.1
  - librsvg ==2.40.10
  - svgutils ==0.1.0
  - bioconductor-gostats ==2.36.0
  - merfishtools ==0.9.0
